baseURL = "/"
languageCode = "en-us"
title = "Alexander Sepelenco"
theme = "poison"
paginate = 10
pluralizelisttitles = false   # removes the automatically appended "s" on sidebar entries

[params]
    brand = "Alexander Sepelenco" # name of your site - appears in the sidebar
    brand_image = "/images/hiking-me.jpg" # path to the image shown in the sidebar
    description = "Software Engineer"
    dark_mode = true # optional - defaults to false

    # MENU PLACEHOLDER
    # Menu dict keys:
        # Name:         The name to display on the menu.
        # URL:          The directory relative to the content directory.
        # HasChildren:  If the directory's files should be listed.  Default is true.
        # Limit:        If the files should be listed, how many should be shown.
    menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
    ]

    # Links to your socials.  Comment or delete any you don't need/use. 
    github_url = "https://github.com/alexandersep"
    gitlab_url = "https://gitlab.scss.tcd.ie/sepelena"
    linkedin_url = "https://www.linkedin.com/in/alexander-sepelenco-0765bb237/" 
    youtube_url = "https://youtube.com/@Silent."

    # NOTE: If you don't want to use RSS, comment or delete the following lines
    # Adds an RSS icon to the end of the socials which links to {{ .Site.BaseURL }}/index.xml
    rss_icon = true
    # Which section the RSS icon links to, defaults to all content. See https://gohugo.io/templates/rss/#section-rss
    rss_section = "posts"

    # Hex colors for your sidebar.
    sidebar_bg_color = "#121212"            # default is #121212
    sidebar_img_border_color = "#515151"    # default is #515151
    sidebar_p_color = "#909090"             # default is #909090
    sidebar_h1_color = "#FFF"               # default is #FFF
    sidebar_a_color = "#FFF"                # default is #FFF
    sidebar_socials_color = "#FFF"          # default is #FFF

    # Hex colors for your content in dark mode
    text_color_dark = "#eee"            # default is #eee
    content_bg_color_dark = '#202020'   # default is #202020
    post_title_color_dark = "#DBE2E9"   # default is #DBE2E9
    list_color_dark = "#9d9d9d"         # default is #9d9d9d
    link_color_dark = "#268bd2"         # default is #268bd2
    date_color_dark = "#9a9a9a"         # default is #9a9a9a
    table_border_color_dark = "#515151" # default is #515151
    table_stripe_color_dark = "#202020" # default is #202020

[taxonomies]
    series = 'series'
    tags = 'tags'
